---
- name: Deploy templates jinja2
  hosts: myServer
  become: true
  tasks:
    - name: Copy template
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
      notify:
        - restart httpd

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
...
