---
- name: PLAYBOOK fail when
  hosts: myServer
  tasks:

    - name: Making sure the /tmp has more than 1gb
      shell: "df -h /tmp|awk '{print $4}'|cut -d G -f1|sed 's/,/./g'|tail -1"
      register: tmpspace
      failed_when: "tmpspace.stdout | float < 1"

    - name: Show value of tmpspace.stdout
      debug:
        msg: "{{ tmpspace.stdout }}"

    - name: Making sure the /opt has more than 4gb
      shell: "df -h /opt|awk '{print $4}'|cut -d G -f1|sed 's/,/./g'|tail -1"
      register: optspace
      failed_when: "optspace.stdout|float < 4"

    - name: Show value of tmpspace.stdout
      debug:
        msg: "{{ optspace.stdout }}"

    - name: Making sure the Physical Memory more than 2gb
      shell: "cat /proc/meminfo|grep -i memtotal|awk '{print $2/1024/1024}'"
      register: memory
      #failed_when: "memory.stdout|float < 2"
      failed_when: "memory.stdout|float < 0.5"

    - name: Show value of tmpspace.stdout
      debug:
        msg: "{{ memory.stdout }}"
