---
dependencies:
  - geerlingguy.php

galaxy_info:
  # See: https://github.com/ansible/galaxy/issues/2393
  # role_name: php-pgsql
  author: geerlingguy
  description: PHP PostgreSQL support for Linux.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - database
    - web
    - postgres
    - php
    - pgsql
