---
- name: PLAYBOOK para el caso 8
  hosts: myServer
  vars_files:
    - vars/test9_vars.json
  tasks:
    - name: Genera archivo JINJA2
      template:
        src: templates/test9.j2
        dest: /home/formacion/ansible-deep-dive-student/BONUS_JINJA/files_generated/file_test9.conf
