---
- name: Python code troubleshooting
  hosts: localhost
  vars:
    test_file_path: "/tmp/test_file.txt"
  tasks:
    - name: Create a single file
      copy:
        content: "This is the file content\n"
        dest: "{{ test_file_path }}"
    - name: Archive the file
      archive:
        path: "{{ test_file_path }}"
        dest: "{{ test_file_path }}.tar"
        format: tar
        remove: yes
    - name: Cleanup
      file:
        path: "{{ test_file_path }}.tar"
        state: absent
