---
- name: Configurar facts
  hosts: myServer
  become: true
  tasks:
  - name: Show distribution
    debug:
      var: ansible_facts['distribution']

  - name: Create user
    user:
      name: "{{ item['username'] }}"
      groups: "{{ item['groups'] }}"
      state: present
    loop: "{{ user_list }}"
    when: ansible_facts['distribution'] == "CentOS"
...

