---
- name: PLAYBOOK Provision DEH
  hosts: aws
  become: true
  tasks:
    - name: Install latest version of Apache
      apt: 
        name: apache2
        update_cache: yes
        state: latest

#    - name: Copy your index page
#      template:
#        src: "files/index.html.j2"
#        dest: "/var/www/{{ http_host }}/index.html"

  handlers:
    - name: restart-apache
      service:
        name: apache2
        state: restarted
